import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AppProvider from "@/context/appContext";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Página Inicial",
  description: "Generated by create next app",
};

interface ContentLayout {
  children: React.ReactNode;
}

export default function ContentLayout({ children }: Readonly<ContentLayout>) {
  return (
    <AppProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className={'text-gray-700 bg-gray-100 h-screen overflow-y-auto'}>
            {children}
          </div>
        </body>
      </html>
    </AppProvider>
  );
}
